variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "subnet_cidr_block2" {}
variable "subnet_cidr_block3" {}
variable "avail_zone" {}
variable "avail_zone2" {}
variable "avail_zone3" {}
variable "env_prefix" {}
variable "instance_type" {}